# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qd83y3B9M5c2P_kDPfOKq0nWc8O1cp_y
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing Image and Converting it in Gray Colour
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline
imagePath='/0_Friends-cast.webp'
image=cv2.imread(imagePath)
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
plt.axis('off')
plt.imshow(gray,cmap='gray')
plt.show()
#Detecting and Marking Faces
faceCascade=cv2.CascadeClassifier("/haarcascade_frontalface_default.xml")
faces = faceCascade.detectMultiScale(gray, scaleFactor = 2, minNeighbors=5, minSize=(25,25))
n = len(faces)
if(n<=1):
    print("{0} Face is found ".format(n))
else:
    print("{0} Number of Faces are found ".format(n))
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x, y), (x+w,y+h), (0,0,250), 3)
status = cv2.imwrite("faces_detected.jpg", image)
print("The Status of Image Stored:{0}".format(status))
imagePath2 = "faces_detected.jpg"
faces_detected = cv2.imread(imagePath2)
faces_detected = cv2.cvtColor(faces_detected,cv2.COLOR_BGR2RGB)
plt.axis("off")
plt.imshow(faces_detected)