# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy-3gem5XifhOPCzY5C0nf5EIy549bIQ
"""

print("              Fibonacci Series")
n=input("Enter the Range of Fibonacci Series : ")
i1=-1
i2=1
n=int(n)
i=1
i3=0


while i<=n:
  i3=i1+i2
  print(i3)
  i1=i2
  i2=i3
  i+=1

