# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy-3gem5XifhOPCzY5C0nf5EIy549bIQ
"""

print("                  Positive Numbers ")
i=input("Enter a List of Integers Seperated by Space : ").split()
for num in i:
  num=int(num)
  if num>=0:
    print(num)