# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15b4zvb3bLbGkzvzz44n_-orNhN5wGw_R
"""

#Python Program to Illustrate Set Operations
A={0,1,2,3,4,5,6}
B={4,6,7,8,9}
Union=A.union(B)
print("Union of A and B : ",Union)
Intersection=A.intersection(B)
print("Intersection of A and B : ",Intersection)
Difference=A.difference(B)
print("Difference of A and B = ",Difference)
Symmetric_Difference=A.symmetric_difference(B)
print("Symmetric Difference of A and B = ",Symmetric_Difference)